kafka-streams-service:
  version: v1
  custom-audience: kafka-streams-service

server:
  port: 8187
  servlet:
    context-path: /kafka-streams-service

kafka-streams-config:
  application-id: kafka-streams-application
  input-topic-name: mastodon-topic
  output-topic-name: mastodon-analytics-topic
  state-file-location: ${HOME}/kafka-streaming-state
  word-count-store-name: word-count-store