server:
  port: 8183

elastic-query-service:
  version: v1
  custom-audience: elastic-query-service

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8086/realms/microservices_realm
          jwk-set-uri: http://localhost:8086/realms/microservices_realm/protocol/openid-connect/certs